# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6f3df701a3f82513ff03e741e094e7717059424c7ad120e597a90ac0e69d2be73de3d16491215d2259c6f6bcd4a78b1f70b38c386635248586c6bad54fcc3a0

test:
  secret_key_base: 9eb9f70829a0fa5fb64e500fee578f2c0823b00f9fade2c314acb1e9c1e547c40909d8b07cc28fe7d6bcf074171ab68b42207779b37d961194a8ed2b1ea7fc5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
